# general
seed: 1
device: 'cuda'
output_path: '~/vlr-project/outputs/cap-edit/france/edited_images'

# data
metadata_path: '~/vlr-project/outputs/caption-llm_edit/france/metadata.csv'
latents_path: '~/vlr-project/outputs/cap-edit/france/latents_forward'
image_path_col: 'src_image_path'
llm_edits_col: 'llm_edit'
country_col: 'src_country'

# diffusion
sd_version: '2.1'
guidance_scale: 10
n_timesteps: 50
prompt: ''
negative_prompt: ''

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
