metadata: "/home/skhanuja/vlr-project/outputs/e2e-instruct/test/japan/metadata.csv"
prompt: This image is culturally relevant to Japan.
output_dir: /home/skhanuja/vlr-project/outputs/e2e-instruct/test/japan