source_countries: ['india']
source_data_path: data/
output_dir: ./outputs/controlnet/france
prompt: make the image culturally relevant to France
seed: 0
num_inference_steps: 100
text_guidance: 7.5
debug: False
